apiVersion: v1
kind: Service
metadata:
  name: devops-service  # Can be renamed to any meaningful service name
spec:
  selector:
    app: devops-app  # Must match the label in the deployment.yaml (matchLabels)
  ports:
    - protocol: TCP
      port: 8081  # External port to expose the service, can be changed
      targetPort: 8081  # Should match the containerPort in deployment.yaml
  type: NodePort  # NodePort type exposes the service on a port on all nodes
